### ISSUE TITLE
Wizard

### ISSUE THREAD

**Issue by henrixapp** [MaMpf-HD/mampf#201]
How to use MaMpf correctly? Give an interactive guideline

**Comment by Splines** [comment]
@fosterfarrell9 According to your opinion, could you create a list with the most important items that should definitely be in such a wizard for creating a new medium? Maybe you could also define some broad steps/categories, e.g. "Naming (and other meta information", "Upload", "Chapters" etc.

**Comment by Splines** [comment]
In #628, we've improved the UX for the administration of a lecture in the role of a teacher of lecture editor. Instead of a wizard, we've split the components into multiple pages in order to tidy it up. During that process, we agreed that we leave the media creation dialog as-is for right now as it is already easy to work with it. We might improve it in the future based on user feedback.
