### ISSUE TITLE
Emergency Button/ Did not understand button

### ISSUE THREAD

**Issue by henrixapp** [MaMpf-HD/mampf#329]
During a lecture students struggle to understand certain topics and are to intimidated to ask questions/mind asking something in the forum. Therefore, a Emergency/Didnot understand button is proposed to collect timemarks, where students have problems.

The button should be easily  accessible and have some introduction. For lecturers there should be the possibility to see the number of marks per video and quickly access those places in order to prepare extra content or clarify it in the discussion.

It might be worth discussing, whether other students should see the marks or not.

This is a first step towards #221 .

**Comment by henrixapp** [comment]
Should users be allowed to enter some question text to help the editor/lecturer to clarify their content?

**Comment by Splines** [comment]
Thanks for the great idea, it's now reality (already since April 2024) and is called "annotation tool". You can read more about it in our blog [here](https://mampf.blog/2024/04/02/annotation-tool/) or just start creating your own annotations in videos and share them with teachers (and lecture editors).
