### ISSUE TITLE
upgrading js packages

### ISSUE THREAD

**Issue by zebleck** [MaMpf-HD/mampf#421]
To prevent security vulnerabilities, it would good to be able to updated our javascript-packages to their newest versions.

Running `yarn outdated` shows:
![image](https://user-images.githubusercontent.com/10833180/206704259-2e66c767-bd4b-40c9-9763-9b2ff752d82a.png)

It seems that the patch update and minor updates are compatible with our current setup as has been done so far in branch https://github.com/MaMpf-HD/mampf/tree/updates-ws202223
![image](https://user-images.githubusercontent.com/10833180/206704491-55e9327e-3123-4525-a1cd-2785108298c8.png)

**Comment by Splines** [comment]
Good point, yeah we update the JS dependencies and also the Bundler dependencies (Gemfile) regularly, e.g. the last time in #672 and #673. There are still some dependencies that we cannot update to a new major version due to [`webpacker`](https://github.com/rails/webpacker) not being maintained anymore. We should move away from it soon and the respective issue for that is #454.
