### ISSUE TITLE
Language setting not reflected in left navbar for lectures

### ISSUE THREAD

**Issue by Splines** [MaMpf-HD/mampf#450]
In your user profile, switch from German to English. Go to a lecture and you still see the left navbar in German, e.g. "Übungen" instead of "Exercises".

**Comment by fosterfarrell9** [comment]
This is by design. The teacher of a lecture sets the language for it, and this overrules the user's setting, see this method in `lecture_controller.rb`:

```
  def set_view_locale
    I18n.locale = @lecture.locale_with_inheritance || current_user.locale ||
                    I18n.default_locale
  end
```
Otherwise, languages will get mixed up constantly, e.g to something like "Chapter 1. Grundlagen". Of course, with more bookkeping it would be possible to make it more fine-grained, e.g. using the user's locale for the left navbar and the above locale for the rest. But still, languages would mix. So, the current design is done towards uniformity. Of course, we can discuss this in basecamp.

**Comment by Splines** [comment]
Ah ok, thanks for clarifying. I think that's ok for now, so will close this issue (we can open it again anytime we feel the need to use the user language in the sidebar).
